# per eseguire docker servono i permetti di root
sudo: required

services:
  - docker # travis installa docker per l'esecuzione

before_install:
  - docker build -t fiaschettodevin/docker-react -f Dockerfile.dev .

script:
  - docker run fiaschettodevin/docker-react npm run test -- --coverage
